variables:
  GO_VERSION: "1.19"

# run the pipeline only on MRs, tags, and default branch
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - documentation
  - test
  - release

include:
  - project: 'gitlab-org/quality/pipeline-common'
    file: '/ci/danger-review.yml'  # danger-review job below

danger-review:
  variables:
    CI_DEBUG_TRACE: "true"
  after_script:
    - 'echo "diff base ${CI_MERGE_REQUEST_DIFF_BASE_SHA}"'
    - 'echo "source head ${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}"'
    - 'echo "source head:-default ${CI_COMMIT_SHA}"'
    - git remote add neil https://gitlab.com/realtime-neil/glab-cli.git
    - git fetch --unshallow --all && find .git/refs -type f -exec ls -l {} \; -exec cat {} \;
    - git fetch refs/merge_requests/$CI_MERGE_REQUEST_IID/train || git fetch 'refs/merge_requests/*'

exit_the_merge_train:
  image: alpine:latest
  script:
    - exit 1
