workflow:
  rules:
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For default branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    # - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # Temporarly create Ci for every branch:
    - if: '$CI_COMMIT_BRANCH'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'
    # For stable branches, create a pipeline.
    - if: '$CI_COMMIT_BRANCH =~ /^[\d-]+-stable$/'
    #

default:
  image: golang:1.15

# Disable DIND for SAST because we need to execute a before_script in the gosec-sast job
variables:
  SAST_DISABLE_DIND: "true"

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

gosec-sast:
  before_script:
    - apk add make
    - make install

code_navigation:
  image: golang:latest
  allow_failure: true
  script:
    - go get github.com/sourcegraph/lsif-go/cmd/lsif-go
    - lsif-go
  artifacts:
    reports:
      lsif: dump.lsif

build_docs:
  allow_failure: true
  script:
    - git config user.name github-actions
    - git config user.email github-actions@github.com
    - make gen-docs
    - git add docs
    - 'git commit -m "docs(update): ${{ steps.get_version.outputs.version }}" || echo "No document(s) updates found!"'
    - git push
