linters:
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - typecheck
        - unused
        - exhaustive
        - exportloopref
        - prealloc

run:
    timeout: 5m
    modules-download-mode: readonly
