run:
    timeout: 5m
    modules-download-mode: readonly

linters:
    disable-all: true
    enable:
        - errcheck
        - gofumpt
        - goimports
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - typecheck
        - unused
